name: Crowdin upload

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  upload-to-crowdin:
    runs-on: [self-hosted, production]
    container: docker.tw.ee/actions_java15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: crowdin action
        uses: crowdin/github-action@1.4.1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          base_url: 'https://transferwise.crowdin.com'
          token: ${{ secrets.CROWDIN_ENTERPRISE_TOKEN }}
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
